
<!DOCTYPE html>
<html>
<?php include 'head.php';?>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <?php include 'nav.php';?>
    <div class="wrapper">
      <div class="container">
    <!--INSERT CODE HERE-->

        <div id = "maincontent">
                    <div class="card" style="height: auto 0;">
                        <div class="card-header" style="background-color: #242424;">
                                  <h2 class="title">TERMS AND CONDITIONS</h2>
                        </div>
                        <div class="card-content">
            <!-- INSERT CODE HERE -->
                            <p>Welcome to the OZZ FITNESS CENTRE web site at http://www.ozzfitness.com (‘Site’) which is owned by OZZ FITNESS CENTRE. This Site is operated by OZZ FITNESS CENTRE and materials on the Site are primarily owned by OZZ FITNESS CENTRE. The Site may also include materials owned by third parties and posted on the Site by virtue of a license, grant or some other form of agreement between the third party and OZZ FITNESS CENTRE. OZZ FITNESS CENTRE has created this Site for your personal enjoyment, entertainment and education. However, you are only authorized to access this Site or to use the materials contained in the Site (regardless of whether your access or use is intended) if you agree to abide by all applicable laws, and to these Terms of Use and Privacy Policy which constitute an Agreement between you and OZZ FITNESS CENTRE. Please read these Terms of Use carefully and save them. If you do not agree with them, you should leave this Site immediately. Any questions or comments regarding, or problems with, this Site should be sent to the Site Administrator at support@goldsgym.com.</p>
                            <p>OZZ FITNESS CENTRE reserves the right to modify or amend this Agreement without notice at any time. It is therefore important that you read this page regularly to ensure you are updated as to any changes.</p>
                            <p>If you become aware of misuse of this Site by any person, please contact the Site Administrator at support@goldsgym.com with your concerns.</p>
                            <p><b>ACCESS AND USE</b></p>
                            <p>All materials contained in this Site are protected by U.S. and international trademark and copyright laws and must only be used for personal, non-commercial purposes. This means that you may only view or download material from this Site for your own use and you must keep all copyright and other proprietary notices attached to the downloaded material.</p>
                            <p>You may not use any deep-link, page-scrape, spider, robot, crawl, index, Internet agent, or other automatic device, program, algorithm or technology which does the same things, to use, access, copy, acquire information, generate impressions, input information, store information, search, generate searches, or monitor any portion of the OZZ FITNESS CENTRE website.</p>
                            <p>The reproduction, duplication, distribution (including by way of email, facsimile or other electronic means), publication, modification, copying or transmission of material from this Site is STRICTLY PROHIBITED unless you have obtained the prior written consent of OZZ FITNESS CENTRE or unless it is expressly permitted by this Site. The material covered by this prohibition includes, without limitation, any text, graphics, logos, photographs, audio or video material or stills from audiovisual material available on this Site. The use of materials from this Site on any other web site or networked computer environment is similarly prohibited. Requests for permission to reproduce or distribute materials found on this Site can be made by contacting OZZ FITNESS CENTRE in writing at Business &amp; Legal Affairs OZZ FITNESS CENTRE at 4001 Maple Ave., Suite 200, Dallas, TX 75219, or email at support@goldsgym.com.</p>
                            <p>You are also strictly prohibited from creating works or materials that derive from or are based on the materials contained in this Site including, without limitation, fonts, icons, link buttons, wallpaper, desktop themes, on-line postcards and greeting cards and unlicensed merchandise. This prohibition applies regardless of whether the derivative materials are sold, bartered or given away.</p>
                            <p>You agree that any Message whatsoever submitted by you becomes the property of OZZ FITNESS CENTRE and may be used, copied, sublicensed, adapted, transmitted, distributed, publicly performed, published, displayed or deleted as OZZ FITNESS CENTRE sees fit.</p>
                            <p><b>UNSOLICITED SUBMISSIONS</b></p>
                            <p>If unsolicited submissions are sent to OZZ FITNESS CENTRE via this Site, these submissions become the property of OZZ FITNESS CENTRE and may be used, copied, sublicensed, adapted, transmitted, distributed, publicly performed, published, displayed or deleted as OZZ FITNESS CENTRE sees fit. You agree that you are not entitled to any compensation, credit or notice whatsoever and that by sending an unsolicited submission you waive the right to make any claim against OZZ FITNESS CENTRE, its parents or affiliates relating to unsolicited submissions, including, without limitation, unfair competition, breach of implied contract or breach of confidentiality.</p>
                            <p><b>EMPLOYMENT OPPORTUNITIES</b></p>
                            <p>OZZ FITNESS CENTRE may, from time to time, post OZZ FITNESS CENTRE employment opportunities on the Site and/or invite users to submit resumes to it. If you choose to submit your name, contact information, resume and/or other personal information to OZZ FITNESS CENTRE in response to employment listings, you are authorizing OZZ FITNESS CENTRE to utilize this information for all lawful and legitimate hiring and employment purposes. OZZ FITNESS CENTRE also reserves the right, at its sole discretion, to forward the information you submit to its parents, subsidiaries and affiliates for legitimate business purposes. Nothing in these Terms of Use or contained in the Site shall constitute a promise by OZZ FITNESS CENTRE to interview, hire or employ any individual who submits information to it, nor shall anything in these Terms of Use or contained in the Site constitute a promise that OZZ FITNESS CENTRE will review any or all of the information submitted to it by users.</p>
                            <p><b>LINKED SITES AND ADVERTISING</b></p>
                            <p>If you are interested in creating hypertext links to this Site, you must contact OZZ FITNESS CENTRE Marketing at 4001 Maple Ave., Suite 200, Dallas, TX 75219 before doing so. In establishing hypertext links, you must not represent in any way, expressly or by implication, that you have received the endorsement, sponsorship or support of this Site or OZZ FITNESS CENTRE, including its respective employees, agents, directors, officers and shareholders.</p>
                            <p>If OZZ FITNESS CENTRE has provided links or pointers to other web sites, no inference or assumption should be made and no representation should be implied that OZZ FITNESS CENTRE is connected with, operates or controls these web sites. OZZ FITNESS CENTRE is not responsible for the content or practices of third party web sites that may be linked to this Site. This Site may also be linked to other web sites operated by companies affiliated or connected with OZZ FITNESS CENTRE. When visiting other web sites, however, you should refer to each such web site’s individual “Terms of Use” and not rely on this Agreement.</p>
                            <p>OZZ FITNESS CENTRE does not endorse and takes no responsibility for third party advertisements which are posted on this Site, nor does it take any responsibility for the goods or services provided by its advertisers.  OZZ FITNESS CENTRE reserves the right, at any time, for any reason not prohibited by law, to deny permission to anyone linking a website to goldsgym.com.</p>
                            <p><b>TERMINATION</b></p>
                            <p>OZZ FITNESS CENTRE reserves the right to immediately terminate your use of, or access to, this Site at any time if OZZ FITNESS CENTRE decides at its sole discretion that you have breached this Agreement or any relevant law, rule or regulation or you have engaged in conduct that OZZ FITNESS CENTRE considers to be inappropriate or unacceptable.</p>
                            <p><b>COPYRIGHT INFRINGEMENT</b></p>
                            <p>If you believe that any material contained in this Site infringes your copyright, you should notify OZZ FITNESS CENTRE of your copyright infringement claim in accordance with the following procedure. OZZ FITNESS CENTRE will process notices of alleged infringement which it receives and will take appropriate action as required by the Digital Millennium Copyright Act (“DMCA”) and other applicable intellectual property laws. The DMCA requires that notifications of claimed copyright infringement should be sent to this Site’s Designated Agent who is: Director of Legal Affairs, OZZ FITNESS CENTRE, 4001 Maple Ave., Suite 200, Dallas, TX 75219 or e-mail: support@goldsgym.com.</p>
                            <p>To be effective, the notification must be in writing and contain the following information (DMCA, 17 U.S.C. 512(c)(3)): 1. Physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; 2. Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site; 3. Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit the service provider to locate the material; 4. Information reasonably sufficient to permit the service provider to contact the complaining party, such as an address, telephone number, and, if available, an electronic mail address at which the complaining party may be contacted; 5. A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; 6. A statement that the information in the notification is accurate, and under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p>
                            <p>E-mails sent with subject ‘DMCA” to support@goldsgym.com for purposes other than communication about copyright claims may not be acknowledged or responded to.</p>
                            <p>If your content has been removed from the Site in response to GOLD&#8217;S GYM&#8217;s receipt of a DMCA Notification as outlined above, and you believe the removal was inappropriate, you may submit a DMCA Counter-Notification by contacting GOLD&#8217;S GYM at:</p>
                            <p>GOLD&#8217;S GYM<br />Attn: Director of Legal Affairs <br />4001 Maple Ave., Suite 200 <br />Dallas, TX 75219 <br />support@goldsgym.com</p>
                            <p>Please include the following information:</p>
                            <ul>
                            <li>Your name, address, telephone number and email address;</li>
                            <li>A statement that you consent to the jurisdiction of Federal District Court for the judicial district in which your address is located, or if your address is outside of the United States, for any judicial district for which jurisdiction for GOLD&#8217;S GYM would be appropriate, and that you will accept service of process from the person who submitted the DMCA notification or an agent of such person;</li>
                            <li>A description of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;</li>
                            <li>A statement by you under penalty of perjury that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled; and</li>
                            <li>Your written or electronic signature attesting to the above.</li>
                            </ul>
                            <p><b>DISCLAIMER OF LIABILITY AND WARRANTIES</b></p>
                            <p>While OZZ FITNESS CENTRE does its best to ensure the optimal performance of the Site, you agree that you use this Site and rely on material contained in this Site at your own risk. To the maximum extent permitted by law, the Site, and all materials in this Site, are provided “as is” and, to the fullest extent permitted by law, are provided without warranties of any kind either express or implied. This means, without limitation, that OZZ FITNESS CENTRE DOES NOT WARRANT that the Site is fit for any particular purpose; that the functions contained in the materials in the Site will be uninterrupted; that defects will be corrected; that the Site is free of viruses and other harmful components or that the Site is accurate, error free or reliable. You acknowledge that OZZ FITNESS CENTRE, its parents and affiliates together with their respective employees, agents, directors, officers and shareholders, IS NOT LIABLE for any delays, inaccuracies, failures, errors, omissions, interruptions, deletions, defects, viruses, communication line failures or for the theft, destruction, damage or unauthorized access to your computer system or network.</p>
                            <p>You acknowledge that OZZ FITNESS CENTRE is not liable for any defamatory, offensive or illegal conduct or material found in connection with this Site, including such conduct or material transmitted by any means by any other person.</p>
                            <p>You acknowledge that OZZ FITNESS CENTRE is not liable for any damages, including, without limitation, direct, incidental, special, consequential or punitive damages, in connection with or arising from your use or from your inability to use the Site.</p>
                            <p><b>NO WARRANTY</b></p>
                            <p>WE, OUR SUBSIDIARIES, OFFICERS, DIRECTORS, EMPLOYEES AND OUR SUPPLIERS PROVIDE OUR WEB SITE AND SERVICES “AS IS” AND WITHOUT ANY WARRANTY OR CONDITION, EXPRESS, IMPLIED OR STATUTORY. WE, OUR SUBSIDIARIES, OFFICERS, DIRECTORS, EMPLOYEES AND OUR SUPPLIERS SPECIFICALLY DISCLAIM ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. Some states do not allow the disclaimer of implied warranties, so the foregoing disclaimer may not apply to you. This warranty gives you specific legal rights and you may also have other legal rights that vary from state to state.</p>
                            <p><b>LIMITATION OF LIABILITY</b></p>
                            <p>IN NO EVENT SHALL WE, OUR SUBSIDIARIES, OFFICERS, DIRECTORS, EMPLOYEES OR OUR SUPPLIERS BE LIABLE FOR LOST PROFITS OR ANY SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR IN CONNECTION WITH OUR SITE, OUR SERVICES OR THIS AGREEMENT (HOWEVER ARISING, INCLUDING NEGLIGENCE).</p>
                            <p>OUR LIABILITY, AND THE LIABILITY OF OUR SUBSIDIARIES, OFFICERS, DIRECTORS, EMPLOYEES, AND SUPPLIERS, TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO $50. Some states do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.  .  YOU HEREBY WAIVE ANY AND ALL RIGHTS TO BRING ANY CLAIM OR ACTION RELATED TO THIS SITE BEYOND ONE (1) YEAR AFTER THE FIRST OCCURRENCE OF THE KIND OF ACT, EVENT, CONDITION OR OMISSION UPON WHICH SUCH CLAIM OR ACTION IS BASED.</p>
                            <p><b>INDEMNITY</b></p>
                            <p>You agree to defend, indemnify and hold harmless OZZ FITNESS CENTRE, its parents and affiliates together with their respective franchisees, employees, agents, directors, officers and shareholders, from and against all the liabilities, claims, damages and expenses (including reasonable attorney’s fees and costs) arising out of your use of this Site; your failure to use the Site; your breach or alleged breach of this Agreement or your breach or alleged breach of the copyright, trademark, proprietary or other rights of third parties.</p>
                            <p><b>LEGAL COMPLIANCE</b></p>
                            <p>You shall comply with all applicable domestic and international laws, statutes, ordinances and regulations regarding your use of our service and your bidding on, listing, purchase, solicitation of offers to purchase, and sale of items.</p>
                            <p><b>SWEEPSTAKES AND/OR CONTESTS</b></p>
                            <p>Sweepstakes, contests, games and other promotions run on OZZ FITNESS CENTRE web sites may require the visitor to provide some personally identifiable information such as full name, address, e-mail address, and phone number, in order to participate. OZZ FITNESS CENTRE may use a reputable third party to manage and administer some or all of its sweepstakes and/or contests. This third party may have access to some or all of the personally identifiable information that is provided by the visitor in order to participate in the sweepstakes and/or contest. In those instances, the third party will be instructed by OZZ FITNESS CENTRE to use the personally identifiable information only for the specific sweepstakes and/or contest related purpose for which it was requested, and in compliance with the OZZ FITNESS CENTRE Privacy Policy. Most often this information is used only to select and contact winners of the sweepstakes and/or contests. Any other use of the personally identifiable information by the third party is strictly prohibited. Our sweepstakes and/or contests are targeted to individuals 18 years of age and older, and individuals under 18 years of age are not eligible to participate. OZZ FITNESS CENTRE requires proof of age in order for an individual to collect any prizes awarded. Individuals may only be a prize winner once in any ninety (90) day period.</p>
                            <p><b>GENERAL PROVISIONS</b></p>
                            <p>This Agreement operates to the fullest extent permissible by law. If any provision of this Agreement is unlawful, void or unenforceable, that provision is deemed severable from this Agreement and does not affect the validity and enforceability of any remaining provisions. This Agreement is governed by, and construed in accordance with, the laws of the State of Texas without giving effect to any principles of conflicts of law.</p>
                            <p><b>NOTICES</b></p>
                            <p>Except as explicitly stated otherwise, any notices shall be given by postal mail to OZZ FITNESS CENTRE Attn: Legal Department, 4001 Maple Ave., Suite 200, Dallas, TX 75219 (in the case of OZZ FITNESS CENTRE) or to the email address you provide to OZZ FITNESS CENTRE during the registration process (in your case). Notice shall be deemed given 24 hours after email is sent, unless the sending party is notified that the email address is invalid. Alternatively, we may give you notice by certified mail, postage prepaid and return receipt requested, to the address provided to OZZ FITNESS CENTRE during the registration process. In such case, notice shall be deemed given 3 days after the date of mailing.</p>
                            <p><b>RESOLUTION OF DISPUTES</b></p>
                            <p>In the event a dispute arises between you and OZZ FITNESS CENTRE, our goal is to provide you with a neutral and cost effective means of resolving the dispute quickly. Accordingly, you and OZZ FITNESS CENTRE agree that any claim or controversy at law or equity that arises out of this Agreement or our services (“Claims”) shall be resolved in accordance with the provisions below or as otherwise mutually agreed upon in writing by the parties. Before resorting to formal proceedings, we strongly encourage you to first contact us directly to seek a resolution and we will consider reasonable requests to resolve the dispute through alternative dispute resolution procedures, such as mediation, as an alternative to litigation.</p>
                            <p><b>BINDING ARBITRATION</b></p>
                            <p>All disputes which cannot be resolved between the parties, and causes of action arising out of or connected with the Site, must be submitted to binding arbitration and decided on an individual basis, without the right for any claims to be pursued or decided as a class, consolidated, collective or representative action.  The arbitration shall be conducted in Dallas County, Texas, on a confidential basis pursuant to the Federal Arbitration Act. Any decision or award as a result of any such arbitration proceeding shall be in writing and shall provide an explanation for all conclusions of law and fact and shall include the assessment of costs, expenses, and reasonable attorneys&#8217; fees. An award of arbitration may be confirmed in a court of competent jurisdiction.</p>
                            <p>You agree that this Agreement and all incorporated agreements may be automatically assigned by OZZ FITNESS CENTRE in our sole discretion, Headings are for reference purposes only and in no way define, limit, construe or describe the scope or extent of such section. Our failure to act with respect to a breach by you or others does not waive our right to act with respect to subsequent or similar breaches. This Agreement sets forth the entire understanding and agreement between us with respect to the subject matter hereof.</p>
                            <p><b>DISCLOSURES</b></p>
                            <p>The services hereunder are offered by OZZ FITNESS CENTRE, located at 4001 Maple Ave., Suite 200, Dallas, TX 75219.</p>
                            <p><b>COPYRIGHTS (C) / TRADEMARKS (™)</b></p>
                            <p>(C) 2017 OZZ FITNESS CENTRE. All trademarks are owned by OZZ FITNESS CENTRE or are used under license. All rights reserved. All materials contained in OZZ FITNESS CENTRE’s web sites are protected by copyright and trademark and shall not be used for any purpose whatsoever other than private, non-commercial viewing purposes. Reproduction, duplication, distribution, derivative works, and other unauthorized copying or use of stills, audio, video footage, or any other materials contained herein are expressly prohibited.</p>
                            <p>Certain activities provided via the website may be covered by U.S. Patent 5,930,474</p>
                                        <!-- <div class="clear"></div> -->



            <!--^ INSERT CODE HERE ^-->  
                        </div><!--/card-content-->
                    </div><!--./card-->
        </div>
        <!-- main content -->

    <!--INSERT CODE HERE ^^^^-->
        <?php include 'rightsidebar.php';?>
      </div>
    </div>
    <?php include 'javascript.php';?>
</body>
</html>